apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: keycloak
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: v1
metadata:
  name: keycloak-scripts
kind: ConfigMap
data:
  dns.DNS_PING.cli: |
    embed-server --server-config=standalone-ha.xml --std-out=echo
    batch
    /subsystem=jgroups/channel=ee:write-attribute(name=stack, value=tcp)

    /subsystem=jgroups/stack=udp/protocol=PING:remove()
    /subsystem=jgroups/stack=udp/protocol=$keycloak_jgroups_discovery_protocol:add(add-index=0, properties=$keycloak_jgroups_discovery_protocol_properties)

    /subsystem=jgroups/stack=tcp/protocol=MPING:remove()
    /subsystem=jgroups/stack=tcp/protocol=$keycloak_jgroups_discovery_protocol:add(add-index=0, properties=$keycloak_jgroups_discovery_protocol_properties)
    run-batch
    stop-embedded-server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 2
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      volumes:
      - name: scripts
        configMap:
          name: keycloak-scripts
      - name: secrets
        secret:
          secretName: aws-rds-jks
          items:
          - key: aws_rds.jks
            path: aws_rds.jks
      containers:
      - name: keycloak
        image: jboss/keycloak:6.0.1
        volumeMounts:
        - mountPath: /opt/jboss/tools/cli/jgroups/discovery
          name: scripts
        - mountPath: /tmp/keycloak/aws_rds.jks
          name: secrets
          subPath: aws_rds.jks
        env:
        - name: DB_VENDOR
          value: MYSQL
        - name: DB_ADDR
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: database_host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: database_port
        - name: DB_USER
          value: keycloak
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: database_password
        - name: JDBC_PARAMS
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: database_ssl_params
        - name: JGROUPS_DISCOVERY_PROTOCOL
          value: dns.DNS_PING
        - name: JGROUPS_DISCOVERY_PROPERTIES
          value: dns_query=keycloak.default.svc.cluster.local
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 7600
          name: jgroups
