apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keycloak
spec:
  template:
    spec:
      containers:
      - name: keycloak
        image: jboss/keycloak:6.0.1
        volumeMounts:
        - mountPath: /tmp/keycloak/aws_rds.jks
          name: secrets
          subPath: aws_rds.jks
