apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keycloak
spec:
  template:
    spec:
      containers:
      - name: keycloak
        image: jboss/keycloak:6.0.1
        env:
        - name: JDBC_PARAMS
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: database_ssl_params
