apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keycloak
spec:
  template:
    spec:
      volumes:
      - name: secrets
        secret:
          secretName: aws-rds-jks
          items:
          - key: aws_rds.jks
            path: aws_rds.jks
