apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keycloak
spec:
  template:
    spec:
      containers:
      - name: keycloak
        env:
        - name: DB_ADDR
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: database_host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: database_port
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: database_password
