apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keycloak
spec:
  template:
    spec:
      volumes:
      - name: secrets
        secret:
          secretName: aws-rds-jks
          items:
          - key: aws_rds.jks
            path: aws_rds.jks
      containers:
      - name: keycloak
        volumeMounts:
        - mountPath: /tmp/keycloak/aws_rds.jks
          name: secrets
          subPath: aws_rds.jks
        env:
        - name: JDBC_PARAMS
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: database_ssl_params