apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keycloak
spec:
  template:
    spec:
      volumes:
      - name: scripts
        configMap:
          name: keycloak-scripts
      containers:
      - name: keycloak
        image: jboss/keycloak:6.0.1
        readinessProbe:
          httpGet:
            path: /auth
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        volumeMounts:
        - mountPath: /opt/jboss/tools/cli/jgroups/discovery
          name: scripts
        env:
        - name: DB_VENDOR
          value: MYSQL
        - name: DB_USER
          value: keycloak
        - name: JGROUPS_DISCOVERY_PROTOCOL
          value: dns.DNS_PING
        - name: JGROUPS_DISCOVERY_PROPERTIES
          value: dns_query=keycloak.default.svc.cluster.local
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 7600
          name: jgroups
